/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package praktekkalkulator;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;

/**
 *
 * @author User
 */
public class Kalkulator extends javax.swing.JFrame {

    @FXML
    private Button num0;
    @FXML
    private Button titik;
    @FXML
    private Button num8;
    @FXML
    private Button num5;
    @FXML
    private Button num2;
    @FXML
    private Button num7;
    @FXML
    private Button num1;
    @FXML
    private Button num4;
    @FXML
    private Button num3;
    @FXML
    private Button num6;
    @FXML
    private Button hasil;
    @FXML
    private Button num9;
    @FXML
    private Button bagi;
    @FXML
    private Button kali;
    @FXML
    private Button tambah;
    @FXML
    private Button kurang;
    @FXML
    private Button sin;
    @FXML
    private Button cos;
    @FXML
    private Button tan;
    @FXML
    private Button log;

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Button7 = new javax.swing.JButton();
        Button2 = new javax.swing.JButton();
        Button4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        Button5 = new javax.swing.JButton();
        Button8 = new javax.swing.JButton();
        Button3 = new javax.swing.JButton();
        Button6 = new javax.swing.JButton();
        Button9 = new javax.swing.JButton();
        Button0 = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        samadengan = new javax.swing.JButton();
        Button1 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jumlah = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        tampilan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Log");
        getContentPane().add(jButton1);
        jButton1.setBounds(210, 240, 49, 42);

        Button7.setText("7");
        getContentPane().add(Button7);
        Button7.setBounds(10, 190, 39, 42);

        Button2.setText("2");
        getContentPane().add(Button2);
        Button2.setBounds(60, 90, 39, 42);

        Button4.setText("4");
        getContentPane().add(Button4);
        Button4.setBounds(10, 140, 39, 42);

        jButton6.setText("jButton1");
        getContentPane().add(jButton6);
        jButton6.setBounds(10, 140, 40, 42);

        Button5.setText("5");
        getContentPane().add(Button5);
        Button5.setBounds(60, 140, 39, 42);

        Button8.setText("8");
        getContentPane().add(Button8);
        Button8.setBounds(60, 190, 39, 42);

        Button3.setText("3");
        getContentPane().add(Button3);
        Button3.setBounds(110, 90, 39, 42);

        Button6.setText("6");
        getContentPane().add(Button6);
        Button6.setBounds(110, 140, 39, 42);

        Button9.setText("9");
        getContentPane().add(Button9);
        Button9.setBounds(110, 190, 39, 42);

        Button0.setText("0");
        getContentPane().add(Button0);
        Button0.setBounds(10, 240, 39, 42);

        Clear.setText("C");
        getContentPane().add(Clear);
        Clear.setBounds(60, 240, 39, 42);

        samadengan.setText("=");
        getContentPane().add(samadengan);
        samadengan.setBounds(110, 240, 41, 42);

        Button1.setText("1");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1);
        Button1.setBounds(10, 90, 39, 42);

        jButton15.setText("/");
        getContentPane().add(jButton15);
        jButton15.setBounds(160, 90, 37, 42);

        jButton16.setText("x");
        getContentPane().add(jButton16);
        jButton16.setBounds(160, 140, 39, 42);

        jButton17.setText("-");
        getContentPane().add(jButton17);
        jButton17.setBounds(160, 190, 37, 42);

        jumlah.setText("+");
        getContentPane().add(jumlah);
        jumlah.setBounds(160, 240, 41, 42);

        jButton19.setText("Sin");
        getContentPane().add(jButton19);
        jButton19.setBounds(210, 90, 50, 42);

        jButton20.setText("Cos");
        getContentPane().add(jButton20);
        jButton20.setBounds(210, 140, 51, 42);

        jButton21.setText("Tan");
        getContentPane().add(jButton21);
        jButton21.setBounds(210, 190, 50, 42);
        getContentPane().add(tampilan);
        tampilan.setBounds(10, 30, 250, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    @FXML
    private void Pembagian(ActionEvent event) {
    }

    @FXML
    private void perkalian(ActionEvent event) {
    }

    @FXML
    private void penjumlahan(ActionEvent event) {
    }

    @FXML
    private void pengurangan(ActionEvent event) {
    }

    @FXML
    private void Sin(ActionEvent event) {
    }

    @FXML
    private void Cos(ActionEvent event) {
    }

    @FXML
    private void Tan(ActionEvent event) {
    }

    @FXML
    private void Log(ActionEvent event) {
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button0;
    private javax.swing.JButton Button1;
    private javax.swing.JButton Button2;
    private javax.swing.JButton Button3;
    private javax.swing.JButton Button4;
    private javax.swing.JButton Button5;
    private javax.swing.JButton Button6;
    private javax.swing.JButton Button7;
    private javax.swing.JButton Button8;
    private javax.swing.JButton Button9;
    private javax.swing.JButton Clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jumlah;
    private javax.swing.JButton samadengan;
    private javax.swing.JTextField tampilan;
    // End of variables declaration//GEN-END:variables
}
